language: cpp

sudo: required

before_install:        
    - sudo add-apt-repository ppa:hrg/daily -y        
    - sudo apt-get update -q
    - sudo apt-get install choreonoid libcnoid-dev openrtm-aist openrtm-aist-dev doxygen hrpsys-base libav-tools cmake cmake-data libboost-all-dev libeigen3-dev -y

before_script:
    - EIGEN3_INCLUDE_DIR="/usr/include/eigen3"

script:
    - cd src/ && make && cd ../
    - cd choreonoid/rtc/PDController && cmake . && sudo make install && cd ../
    - cd Kinematics && cmake . && sudo make install
